<!-- $Id$ -->
<?php
#  Copyright (C) 2003  ken restivo <ken@restivo.org>
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
# 
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details. 
# 
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

    global $HTTP_GET_VARS;
    global $HTTP_POST_VARS;
    global $_SERVER;

	#XXX hack
	$cutoffdate = "11/04/2003";
	$auctioncutoff = "12/18/2003";
	$solicitcutoff = "02/14/2004";
	$packagingcutoff = "02/14/2004";

?>

<!-- END GLOBALS -->

